.PHONY: clean All

All:
	@echo "----------Building project:[ IPR - Debug ]----------"
	@cd "IPR" && "$(MAKE)" -f  "IPR.mk"
clean:
	@echo "----------Cleaning project:[ IPR - Debug ]----------"
	@cd "IPR" && "$(MAKE)" -f  "IPR.mk" clean
